spring.application.name=Reservas-MS-Catalog-Service
spring.profiles.active=${SPRING_PROFILE:dev}

# Content Negotiation
spring.mvc.contentnegotiation.favor-path-extension=false
spring.mvc.contentnegotiation.favor-parameter=false
spring.mvc.contentnegotiation.media-types.json=application/json

# Feign Client URLs
services.auth-service.url=${SERVICES_AUTH_URL:http://localhost:8081}

# JWT Configuration
jwt.secret=${JWT_SECRET:default-secret-key-change-in-prod}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Logging base
logging.level.com.codefactory.reservasmscatalogservice=DEBUG
logging.level.org.springframework.web=INFO